# Generated by Django 4.2.3 on 2023-07-17 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_create_date_alter_post_user'),
        ('groups', '0002_alter_group_admin'),
        ('accounts', '0002_user_remove_usercreation_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCreation',
        ),
    ]
